### ISSUE TITLE
for Mac ?

### ISSUE THREAD

**Issue by shreyagarwal** [shathor/JShellStandalone#1]
Do linux settings also work for mac ?

**Comment by shathor** [comment]
It should, can you try? I've no Mac, so no way to test it. Otherwise you can build your own by following the Linux instructions.

**Comment by evandrix** [comment]
<< bump >>

**Comment by osmundf** [comment]
I managed to get this to work as advertised on MacOS

I exported the Java Home that I needed:
> export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home"

Then used JLink (colon for separating module paths):
> "$JAVA_HOME/bin/jlink" --module-path $JAVA_HOME/jmods:./mods --add-modules com.standalone.jshell --output ./target --compress 2 --strip-debug --exclude-files *.diz --no-header-files --no-man-pages

MacOS 10.14.4 + JDK 11.0.2
